openapi: 3.0.1
info:
  title: Mapping
  description: API Definition of Mapping
  version: 1.0.0
servers:
- url: http://localhost:8290/mapping
paths:
  /:
    post:
      responses:
        default:
          description: Default response
